# Generated by Django 4.0.3 on 2022-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nameItens', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('idUsuario', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=40)),
                ('cuerpo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('fechaCreacion', models.DateField()),
                ('imagen', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('telef', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=40)),
                ('usuario', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('perfil', models.CharField(max_length=40)),
                ('imagen', models.CharField(max_length=80)),
            ],
        ),
    ]
